app/main_page_module/forms.py
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm # , RecaptchaField
from flask_wtf.file import FileField, MultipleFileField, FileAllowed, FileRequired

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import BooleanField, IntegerField, StringField, TextAreaField, SelectField, \
     PasswordField, HiddenField, SubmitField, DateField, validators # BooleanField

# Import Form validators
from wtforms.validators import Email, EqualTo, ValidationError


from app.main_page_module.p_objects.artifact import Artifact

from datetime import datetime


#email verification
import re
import os.path


class ArtifactForm(FlaskForm):
    # z_<type>_<num>
    col_ref_num = HiddenField('col_ref_num', [validators.InputRequired(message='Dont fiddle around with the code!')])
    
    name = StringField('Naziv', [validators.InputRequired(message='We need a title.'), validators.Length(max=150)])
    
    type_ = SelectField('Tip:', [
        validators.InputRequired(message='You need to specify the type')], 
                         choices=[])
    
    
    period = SelectField('Obdobje:', [
        validators.InputRequired(message='You need to specify the type')], 
                         choices=[])    
    
    
    state_entity = StringField('Politicna Entiteta', [validators.Length(max=150)])
    replica = SelectField(u'Replika:', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('1', 'Da'), ('0', 'Ne')])
        
    provenance_notes = TextAreaField('Opombe o izvoru')
    owners = StringField('Lastniki, CSV', [validators.Length(max=300)])
    description = TextAreaField('Opis')   
    historical_context = TextAreaField('Zgodovinski kontekst')   
        
    buy_price = IntegerField('Cena ob nakupu', [validators.InputRequired(message='Cena je zahtevana')], default=0)    
    sold_price = IntegerField('Cena ob prodaji', default=0)    
        
    joined_collection_in_year = IntegerField('Leto prejema v kolekcijo', [validators.InputRequired(message='Letnica je zahtevana')], default=datetime.now().year)    
    left_collection_in_year = IntegerField('Leto oddaje iz kolekcije', default=0)    
        
    reference = StringField('Reference', [validators.Length(max=150)], default="")
        
    public = SelectField(u'Javno vidno', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('0', 'Ne'), ('1', 'Da')])      
        
        
    curr_location_of_item = StringField('Trenutna lokacija artifakta', [validators.Length(max=150)])
    
    coin_type = StringField('Tip kovanca', [validators.Length(max=150)])
    coin_description = TextAreaField('Opis kovanca')  
    ruler = StringField('Vladar, pod katerim je bila kovanec izdan', [validators.Length(max=150)])
    mint_city = StringField('Mesto kovnice', [validators.Length(max=100)])
    mint_period = StringField('Leto/obdobje kovanja', [validators.Length(max=50)])
    material = StringField('Material', [validators.Length(max=150)])
    weight = StringField('Teža', [validators.Length(max=50)])
    diameter = StringField('Premer', [validators.Length(max=50)])
    
    obverse = TextAreaField('Obverse - Lice')   
    reverse = TextAreaField('Reverse - Hrbet')   
    
    grade = SelectField(u'Ocena Stanja', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[])          
    
    image = FileField("Slika", validators=[
                FileAllowed(["PNG", "png", "JPG", "jpg", "JPEG", "jpeg"], "Only .png .jpeg and jpg allowed")])         
    
    
    submit = SubmitField('Dodaj Artifakt')
    
    
    def __init__(self, *args, **kwargs):
        super(ArtifactForm, self).__init__(*args, **kwargs)
        self.type_.choices = [[id_, name] for name, id_ in Artifact.types().items()]  
        self.period.choices = [[data_[0], name] for name, data_ in Artifact.periods().items()]       
        self.grade.choices = [[id_, name] for name, id_ in Artifact.grades().items()]        


class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', [validators.InputRequired(message='Forgot your email address?')])
    password = PasswordField('Password', [validators.InputRequired(message='Must provide a password.')])
    remember = BooleanField()
    
    submit = SubmitField('Login')


 
form_dicts = {"Artifact": ArtifactForm,
              "Login": LoginForm
              } 

app/main_page_module/controllers/controllers.py
import json

# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, jsonify, send_file, Response, abort

# Import module forms
from app.main_page_module.forms import form_dicts
#from app.main_page_module.p_objects.note_o import N_obj


from wrappers import login_required, online_required
from app.pylavor import Pylavor
from app.main_page_module.other import Randoms
from app.main_page_module.gears import Gears_obj
from app.main_page_module.p_objects.artifact import Artifact
from app.main_page_module.p_objects.excel_artifaks import ExcelO


from app import app

#import os
import re
import os
import zipfile
import io
import pathlib
from passlib.hash import sha512_crypt
import datetime


# Define the blueprint: 'auth', set its url prefix: app.url/auth
main_page_module = Blueprint('main_page_module', __name__, url_prefix='/')


@app.context_processor
def inject_to_every_page():
    
    return dict(Randoms=Randoms, datetime=datetime, Pylavor=Pylavor, Artifact=Artifact)


@main_page_module.route('/', methods=['GET'])
def offline():
    return render_template("main_page_module/offline.html")

@main_page_module.route('/index', methods=['GET'])
@online_required(app.config['ONLINE'])
def index():
    return render_template("main_page_module/index.html")

@main_page_module.route('/artifacts/<type_>', methods=['GET'])
@main_page_module.route('/artifacts/', methods=['GET'])
@online_required(app.config['ONLINE'])
def artifacts(type_="all"):    
    return render_template("main_page_module/artifacts/artifacts_all.html",
                           type_=type_)

@main_page_module.route('/artifacts_new/', methods=['GET', 'POST'])
@online_required(app.config['ONLINE'])
@login_required
def artifacts_new():
    form = form_dicts["Artifact"]()

    if form.validate_on_submit():
        col_ref_num = Artifact.col_ref_num_new(form.type_.data)
        
        art_data = {"col_ref_num": col_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "period": form.period.data,
            "state_entity": form.state_entity.data,
            "replica": form.replica.data,
            "provenance_notes": form.provenance_notes.data,
            "owners": form.owners.data,
            "description": form.description.data,
            "historical_context": form.historical_context.data,
            "buy_price": form.buy_price.data,
            "sold_price": form.sold_price.data,
            "joined_collection_in_year": form.joined_collection_in_year.data,
            "left_collection_in_year": form.left_collection_in_year.data,
            "reference": form.reference.data,
            "public": form.public.data,
            "curr_location_of_item": form.curr_location_of_item.data,
            "coin_type": form.coin_type.data,
            "coin_description": form.coin_description.data,
            "ruler": form.ruler.data,
            "mint_city": form.mint_city.data,
            "mint_period": form.mint_period.data,
            "material": form.material.data,
            "weight": form.weight.data,
            "diameter": form.diameter.data,
            "obverse": form.obverse.data,
            "reverse": form.reverse.data,
            "grade": form.grade.data
            }

        artifact = Artifact(art_data)
        
        try:
            artifact.save()
            flash('Artifakt uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.artifacts_view", col_ref_num=col_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju artifakta!', 'error')        
        
    
    for error in form.errors:
        print(error)
        flash(f'Invalid Data: {error}', 'error')    

    return render_template("main_page_module/artifacts/artifacts_new.html", form=form)



@main_page_module.route('/artifacts_view/<col_ref_num>', methods=['GET'])
@online_required(app.config['ONLINE'])
def artifacts_view(col_ref_num):
    art_data = Artifact.get_one(col_ref_num)
    
    if art_data is False or (('user_id' not in session) and (art_data["public"] != "1")):
        flash(f'Artifakt ne obstaja.', 'error')
        return redirect(url_for('main_page_module.artifacts'))            
    
    artifact = Artifact(art_data)
    
    return render_template("main_page_module/artifacts/artifacts_view.html", artifact=artifact)


@main_page_module.route('/artifacts_edit/', methods=['POST'])
@main_page_module.route('/artifacts_edit/<col_ref_num>', methods=['GET', 'POST'])
@login_required
@online_required(app.config['ONLINE'])
def artifacts_edit(col_ref_num:str=None):
    form = form_dicts["Artifact"]()
    
    if col_ref_num == None:
        col_ref_num = form.col_ref_num.data
    else:
        form.col_ref_num.data = col_ref_num
    
    art_data = Artifact.get_one(col_ref_num)
    
    if art_data is False:
        flash(f'Artifakt ne obstaja.', 'error')
        return redirect(url_for('main_page_module.artifacts'))

    artifact = Artifact(art_data)

    # GET
    if request.method == 'GET':
        form.process(col_ref_num = art_data["col_ref_num"],
                     name = art_data["name"],
                     type_ = art_data["type_"],
                     period = art_data["period"],
                     state_entity = art_data["state_entity"],
                     replica = art_data["replica"],
                     provenance_notes = art_data["provenance_notes"],
                     owners = art_data["owners"],
                     description = art_data["description"],
                     historical_context = art_data["historical_context"],
                     buy_price = art_data["buy_price"],
                     sold_price = art_data["sold_price"],
                     joined_collection_in_year = art_data["joined_collection_in_year"],
                     left_collection_in_year = art_data["left_collection_in_year"],
                     reference = art_data["reference"],
                     public = art_data["public"],
                     curr_location_of_item = art_data["curr_location_of_item"],
                     coin_type = art_data["coin_type"],
                     coin_description = art_data["coin_description"],
                     ruler = art_data["ruler"],
                     mint_city = art_data["mint_city"],
                     mint_period = art_data["mint_period"],
                     material = art_data["material"],
                     weight = art_data["weight"],
                     diameter = art_data["diameter"],
                     obverse = art_data["obverse"],
                     reverse = art_data["reverse"],
                     grade = art_data["grade"])
    
    # POST
    if form.validate_on_submit():
        art_data = {"col_ref_num": col_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "period": form.period.data,
            "state_entity": form.state_entity.data,
            "replica": form.replica.data,
            "provenance_notes": form.provenance_notes.data,
            "owners": form.owners.data,
            "description": form.description.data,
            "historical_context": form.historical_context.data,
            "buy_price": form.buy_price.data,
            "sold_price": form.sold_price.data,
            "joined_collection_in_year": form.joined_collection_in_year.data,
            "left_collection_in_year": form.left_collection_in_year.data,
            "reference": form.reference.data,
            "public": form.public.data,
            "curr_location_of_item": form.curr_location_of_item.data,
            "coin_type": form.coin_type.data,
            "coin_description": form.coin_description.data,
            "ruler": form.ruler.data,
            "mint_city": form.mint_city.data,
            "mint_period": form.mint_period.data,
            "material": form.material.data,
            "weight": form.weight.data,
            "diameter": form.diameter.data,
            "obverse": form.obverse.data,
            "reverse": form.reverse.data,
            "grade": form.grade.data
            }
        
        artifact = Artifact(art_data)

        try:
            artifact.save()
            
            if form.image.data != None:
                file_ = form.image.data
                artifact.write_image(file_)            
            
            flash('Artifakt uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.artifacts_view", col_ref_num=col_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju artifakta!', 'error')
        
    
    for field, errors in form.errors.items():
        print(f'Field: {field}')
        for error in errors:
            flash(f'Invalid Data for {field}: {error}', 'error')
    
    
    return render_template("main_page_module/artifacts/artifacts_edit.html", form=form, artifact=artifact)


@main_page_module.route('/artifacts_delete_image/<col_ref_num>/<image_name>', methods=['GET'])
@online_required(app.config['ONLINE'])
@login_required
def artifacts_delete_image(col_ref_num, image_name):
    art_data = Artifact.get_one(col_ref_num)
    
    if art_data is False or (('user_id' not in session) and (art_data["public"] != "1")):
        flash(f'Artifakt ne obstaja.', 'error')
        return redirect(url_for('main_page_module.artifacts'))            
    
    artifact = Artifact(art_data)
    
    artifact.delete_image(image_name)
    
    flash(f'Slika izbrisana.', 'success')
    
    return render_template("main_page_module/artifacts/artifacts_view.html", artifact=artifact)


# Set the route and accepted methods
@main_page_module.route('/export_artifacts/', methods=['GET'])
@login_required
def export_artifacts():
    try:
        artifacts = Artifact.get_all("all")
    except Exception as e:
        app.logger.warn(f"{e}")

app/templates/main_page_module/about.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
{% endblock extraheader  %}

{% block nav_about %}text-secondary{% endblock nav_about %}



{% block content%}

  <div class="container-fluid" >
    <br>
    <div class="row">
      <div class="col-sm-2">

      </div>
      
      
      <!-- START inner -->
      <div class="col-sm-8">

        <div class="row">
          <div class="col-sm-6">
            <img src="{{ url_for('static', filename='coat_of_arms_zubin.svg') }}" class="img-fluid" alt="...">
          </div>
          <div class="col-sm-6">
            <h2>O Zbirki</h2>
            <hr>
            <p>Privatna zbirka, ki jo je začel moj nono, jaz pa jo nadaljujem."</p>
            <hr>
            <table class="table">
              <tbody>
                <tr>
                  <td><i class="bi bi-telephone"></i></td>
                  <td></td>
                </tr>
                <tr>
                  <td><i class="bi bi-envelope-at"></i></td>
                  <td><td>
                </tr>
                <tr>
                  <td><i class="bi bi-facebook"></i></td>
                  <td><a href="">Facebook</a></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

      </div>
      <!-- END inner -->


        
      <div class="col-sm-2">

      </div>

 
      </div>
    </div>

  </div>

{% endblock content %}

app/templates/main_page_module/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.ico') }}">


    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='main_page_module/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main_page_module/icons/bootstrap_icons/bootstrap-icons.min.css') }}">
    
    <script src="{{ url_for('static', filename='main_page_module/jquerry/jquery-3.5.1.min.js') }}"></script>


    {% block extraheader %}
    {% endblock extraheader %}

    <title>{{ config['APP_NAME'] }}</title>
  </head>

    
  <body>
    <header class="p-3 text-bg-dark">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            <img src="{{ url_for('static', filename='coat_of_arms_zubin.svg') }}" class="img-fluid" alt="..." style="max-width: 50px;" >
          </a>
  
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{{ url_for('main_page_module.index') }}" class="nav-link px-2 {% block nav_index %}text-white{% endblock nav_index %}"><i class="bi bi-house"></i> Domov</a></li>
            <li><a href="{{ url_for('main_page_module.artifacts', type_='not_coin') }}" class="nav-link px-2 {% block nav_artfs %}text-white{% endblock nav_artfs %}"><i class="bi bi-bookmark-star-fill"></i> Artifakti</a></li>
            <li><a href="{{ url_for('main_page_module.artifacts', type_='coin') }}" class="nav-link px-2 {% block nav_kovanci %}text-white{% endblock nav_kovanci %}"><i class="bi bi-coin"></i> Kovanci</a></li>
            <li><a href="{{ url_for('main_page_module.artifacts', type_='coin') }}" class="nav-link px-2 {% block nav_vse %}text-white{% endblock nav_vse %}"><i class="bi bi-ui-radios"></i> Vse</a></li>
            <li><a href="{{ url_for('main_page_module.about') }}" class="nav-link px-2 {% block nav_about %}text-white{% endblock nav_about %}"><i class="bi bi-info-square"></i> O zbirki</a></li>
          </ul>
          
          <div class="text-end d-flex align-items-center">
            <!-- Login Button -->
            {% if session['user_id'] %}<a type="button" class="btn btn-outline-light me-2" href="{{ url_for('main_page_module.logout') }}">Logout</a>{% endif %}
        </div>
        </div>
      </div>
    </header>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div>
          {% for category, message in messages %}
            {% if category == "error" %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% else %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}

    <br>
    <hr>
    <footer class="footer mt-auto py-3 bg-body-tertiary text-center">
      <div class="container">
        <span class="text-body-secondary">2025 - <script>document.write(new Date().getFullYear())</script> &copy; <a href="{{ url_for('main_page_module.login') }}">{{ config['APP_NAME'] }}</a></span>
      </div>
    </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Bootstrap JS -->
    <script src="{{ url_for('static', filename='main_page_module/bootstrap/js/bootstrap.bundle.min.js') }}"></script>


  </body>
</html>

app/templates/main_page_module/index.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
{% endblock extraheader  %}

{% block nav_index %}text-secondary{% endblock nav_index %}



{% block content%}

  <div class="container-fluid" >
    <br>
    <div class="row">
      <div class="col-sm-2">

      </div>
      <div class="col-sm-8">
        <legend>Izbrani Artifakti</legend> 
        <div class="row">
      
      


          {% for col_ref_num, data in Artifact.get_all("all", 20, True).items() %}
            {% set artifact = Artifact(data) %}

            {% set images, count = artifact.get_images() %}
              <div class="col-sm-4">

                <div class="card">
                  {% if images|length == 0 %}
                    <img src="{{ url_for('static', filename='artifacts/placeholder_vector.svg') }}" class="card-img-top" alt="...">
                  {% else %}
                    <img src="{{ url_for('static', filename='artifacts/images/'+images[0]) }}" class="card-img-top" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{ artifact.name }}</h5>
                    <p class="card-text">{{ artifact.description[:250] }}...</p>
                    <div class="d-grid gap-2">
                      <a href="{{ url_for('main_page_module.artifacts_view', col_ref_num=artifact.col_ref_num) }}" class="btn btn-outline-dark">Pregled</a>
                    </div>
                  </div>
                </div>
              </div>

          {% endfor %}
        </div>

      </div>


        
      <div class="col-sm-2">

      </div>

 
      </div>
    </div>

  </div>

{% endblock content %}

app/templates/main_page_module/offline.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Fade In SVG</title>
  <style>
    html, body {
      margin: 0;
      padding: 0;
      height: 100%;
      background-color: black;
      overflow: hidden;
    }

    #overlay {
      position: fixed;
      top: 0; left: 0;
      width: 100%;
      height: 100%;
      background-color: black;
      opacity: 1;
      transition: opacity 5s ease-in-out;
      z-index: 10;
    }

    #svg-container {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 5;
    }

    svg {
      width: 150px;
      height: 150px;
      fill: white;
    }
  </style>
</head>
<body>

  <!-- SVG in the center -->
  <div id="svg-container">
    <img src="{{ url_for('static', filename='coat_of_arms_zubin.svg') }}" alt="SVG Image" width="450" height="450">
  </div>



  <!-- Dark overlay that fades out -->
  <div id="overlay"></div>

  <script>
      window.addEventListener('load', () => {
    const overlay = document.getElementById('overlay');

    setTimeout(() => {
      // Start the fade-out
      overlay.style.opacity = 0;

      // After the transition ends, remove the overlay from the DOM
      overlay.addEventListener('transitionend', () => {
        overlay.remove();
      });
    }, 1000);

    setTimeout(() => {
      window.location.href = "{{ url_for('main_page_module.index') }}"; // 🔁 Change this URL
    }, 10000); // 10,000 ms = 10 seconds

  });
  </script>

</body>
</html>