app/main_page_module/forms.py
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm # , RecaptchaField
from flask_wtf.file import FileField, MultipleFileField, FileAllowed, FileRequired

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import BooleanField, IntegerField, StringField, TextAreaField, SelectField, \
     PasswordField, HiddenField, SubmitField, DateField, validators # BooleanField

# Import Form validators
from wtforms.validators import Email, EqualTo, ValidationError


from app.main_page_module.p_objects.artifact import Artifact

from datetime import datetime


#email verification
import re
import os.path


class ArtifactForm(FlaskForm):
    # z_<type>_<num>
    col_ref_num = HiddenField('col_ref_num', [validators.InputRequired(message='Dont fiddle around with the code!')])
    
    name = StringField('Naziv', [validators.InputRequired(message='We need a title.'), validators.Length(max=150)])
    
    type_ = SelectField('Tip:', [
        validators.InputRequired(message='You need to specify the type')], 
                         choices=[])
    
    
    period = SelectField('Obdobje:', [
        validators.InputRequired(message='You need to specify the type')], 
                         choices=[])    
    
    
    state_entity = StringField('Politicna Entiteta', [validators.Length(max=150)])
    replica = SelectField(u'Replika:', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('1', 'Da'), ('0', 'Ne')])
        
    provenance_notes = TextAreaField('Opombe o izvoru')
    owners = StringField('Lastniki, CSV', [validators.Length(max=300)])
    description = TextAreaField('Opis')   
    historical_context = TextAreaField('Zgodovinski kontekst')   
        
    buy_price = IntegerField('Cena ob nakupu', [validators.InputRequired(message='Cena je zahtevana')], default=0)    
    sold_price = IntegerField('Cena ob prodaji', default=0)    
        
    joined_collection_in_year = IntegerField('Leto prejema v kolekcijo', [validators.InputRequired(message='Letnica je zahtevana')], default=datetime.now().year)    
    left_collection_in_year = IntegerField('Leto oddaje iz kolekcije', default=0)    
        
    reference = StringField('Reference', [validators.Length(max=150)], default="")
        
    public = SelectField(u'Javno vidno', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('0', 'Ne'), ('1', 'Da')])      
        
        
    curr_location_of_item = StringField('Trenutna lokacija artifakta', [validators.Length(max=150)])
    
    coin_type = StringField('Tip kovanca', [validators.Length(max=150)])
    coin_description = TextAreaField('Opis kovanca')  
    ruler = StringField('Vladar, pod katerim je bila kovanec izdan', [validators.Length(max=150)])
    mint_city = StringField('Mesto kovnice', [validators.Length(max=100)])
    mint_period = StringField('Leto/obdobje kovanja', [validators.Length(max=50)])
    material = StringField('Material', [validators.Length(max=150)])
    weight = StringField('Teža', [validators.Length(max=50)])
    diameter = StringField('Premer', [validators.Length(max=50)])
    
    obverse = TextAreaField('Obverse - Lice')   
    reverse = TextAreaField('Reverse - Hrbet')   
    
    grade = SelectField(u'Ocena Stanja', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[])          
    
    image = FileField("Slika", validators=[
                FileAllowed(["PNG", "png", "JPG", "jpg", "JPEG", "jpeg"], "Only .png .jpeg and jpg allowed")])         
    
    
    submit = SubmitField('Dodaj Artifakt')
    
    
    def __init__(self, *args, **kwargs):
        super(ArtifactForm, self).__init__(*args, **kwargs)
        self.type_.choices = [[id_, name] for name, id_ in Artifact.types().items()]  
        self.period.choices = [[data_[0], name] for name, data_ in Artifact.periods().items()]       
        self.grade.choices = [[id_, name] for name, id_ in Artifact.grades().items()]        


class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', [validators.InputRequired(message='Forgot your email address?')])
    password = PasswordField('Password', [validators.InputRequired(message='Must provide a password.')])
    remember = BooleanField()
    
    submit = SubmitField('Login')


 
form_dicts = {"Artifact": ArtifactForm,
              "Login": LoginForm
              } 

app/main_page_module/controllers/controllers.py
import json

# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, jsonify, send_file, Response, abort

# Import module forms
from app.main_page_module.forms import form_dicts
#from app.main_page_module.p_objects.note_o import N_obj


from wrappers import login_required, online_required
from app.pylavor import Pylavor
from app.main_page_module.other import Randoms
from app.main_page_module.gears import Gears_obj
from app.main_page_module.p_objects.artifact import Artifact
from app.main_page_module.p_objects.excel_artifaks import ExcelO


from app import app

#import os
import re
import os
import zipfile
import io
import pathlib
from passlib.hash import sha512_crypt
import datetime


# Define the blueprint: 'auth', set its url prefix: app.url/auth
main_page_module = Blueprint('main_page_module', __name__, url_prefix='/')


@app.context_processor
def inject_to_every_page():
    
    return dict(Randoms=Randoms, datetime=datetime, Pylavor=Pylavor, Artifact=Artifact)


@main_page_module.route('/', methods=['GET'])
def offline():
    return render_template("main_page_module/offline.html")

@main_page_module.route('/index', methods=['GET'])
@online_required(app.config['ONLINE'])
def index():
    return render_template("main_page_module/index.html")

@main_page_module.route('/artifacts/<type_>', methods=['GET'])
@main_page_module.route('/artifacts/', methods=['GET'])
@online_required(app.config['ONLINE'])
def artifacts(type_="all"):    
    return render_template("main_page_module/artifacts/artifacts_all.html",
                           type_=type_)

@main_page_module.route('/artifacts_new/', methods=['GET', 'POST'])
@online_required(app.config['ONLINE'])
@login_required
def artifacts_new():
    form = form_dicts["Artifact"]()

    if form.validate_on_submit():
        col_ref_num = Artifact.col_ref_num_new(form.type_.data)
        
        art_data = {"col_ref_num": col_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "period": form.period.data,
            "state_entity": form.state_entity.data,
            "replica": form.replica.data,
            "provenance_notes": form.provenance_notes.data,
            "owners": form.owners.data,
            "description": form.description.data,
            "historical_context": form.historical_context.data,
            "buy_price": form.buy_price.data,
            "sold_price": form.sold_price.data,
            "joined_collection_in_year": form.joined_collection_in_year.data,
            "left_collection_in_year": form.left_collection_in_year.data,
            "reference": form.reference.data,
            "public": form.public.data,
            "curr_location_of_item": form.curr_location_of_item.data,
            "coin_type": form.coin_type.data,
            "coin_description": form.coin_description.data,
            "ruler": form.ruler.data,
            "mint_city": form.mint_city.data,
            "mint_period": form.mint_period.data,
            "material": form.material.data,
            "weight": form.weight.data,
            "diameter": form.diameter.data,
            "obverse": form.obverse.data,
            "reverse": form.reverse.data,
            "grade": form.grade.data
            }

        artifact = Artifact(art_data)
        
        try:
            artifact.save()
            flash('Artifakt uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.artifacts_view", col_ref_num=col_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju artifakta!', 'error')        
        
    
    for error in form.errors:
        print(error)
        flash(f'Invalid Data: {error}', 'error')    

    return render_template("main_page_module/artifacts/artifacts_new.html", form=form)



@main_page_module.route('/artifacts_view/<col_ref_num>', methods=['GET'])
@online_required(app.config['ONLINE'])
def artifacts_view(col_ref_num):
    art_data = Artifact.get_one(col_ref_num)
    
    if art_data is False or (('user_id' not in session) and (art_data["public"] != "1")):
        flash(f'Artifakt ne obstaja.', 'error')
        return redirect(url_for('main_page_module.artifacts'))            
    
    artifact = Artifact(art_data)
    
    return render_template("main_page_module/artifacts/artifacts_view.html", artifact=artifact)


@main_page_module.route('/artifacts_edit/', methods=['POST'])
@main_page_module.route('/artifacts_edit/<col_ref_num>', methods=['GET', 'POST'])
@login_required
@online_required(app.config['ONLINE'])
def artifacts_edit(col_ref_num:str=None):
    form = form_dicts["Artifact"]()
    
    if col_ref_num == None:
        col_ref_num = form.col_ref_num.data
    else:
        form.col_ref_num.data = col_ref_num
    
    art_data = Artifact.get_one(col_ref_num)
    
    if art_data is False:
        flash(f'Artifakt ne obstaja.', 'error')
        return redirect(url_for('main_page_module.artifacts'))

    artifact = Artifact(art_data)

    # GET
    if request.method == 'GET':
        form.process(col_ref_num = art_data["col_ref_num"],
                     name = art_data["name"],
                     type_ = art_data["type_"],
                     period = art_data["period"],
                     state_entity = art_data["state_entity"],
                     replica = art_data["replica"],
                     provenance_notes = art_data["provenance_notes"],
                     owners = art_data["owners"],
                     description = art_data["description"],
                     historical_context = art_data["historical_context"],
                     buy_price = art_data["buy_price"],
                     sold_price = art_data["sold_price"],
                     joined_collection_in_year = art_data["joined_collection_in_year"],
                     left_collection_in_year = art_data["left_collection_in_year"],
                     reference = art_data["reference"],
                     public = art_data["public"],
                     curr_location_of_item = art_data["curr_location_of_item"],
                     coin_type = art_data["coin_type"],
                     coin_description = art_data["coin_description"],
                     ruler = art_data["ruler"],
                     mint_city = art_data["mint_city"],
                     mint_period = art_data["mint_period"],
                     material = art_data["material"],
                     weight = art_data["weight"],
                     diameter = art_data["diameter"],
                     obverse = art_data["obverse"],
                     reverse = art_data["reverse"],
                     grade = art_data["grade"])
    
    # POST
    if form.validate_on_submit():
        art_data = {"col_ref_num": col_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "period": form.period.data,
            "state_entity": form.state_entity.data,
            "replica": form.replica.data,
            "provenance_notes": form.provenance_notes.data,
            "owners": form.owners.data,
            "description": form.description.data,
            "historical_context": form.historical_context.data,
            "buy_price": form.buy_price.data,
            "sold_price": form.sold_price.data,
            "joined_collection_in_year": form.joined_collection_in_year.data,
            "left_collection_in_year": form.left_collection_in_year.data,
            "reference": form.reference.data,
            "public": form.public.data,
            "curr_location_of_item": form.curr_location_of_item.data,
            "coin_type": form.coin_type.data,
            "coin_description": form.coin_description.data,
            "ruler": form.ruler.data,
            "mint_city": form.mint_city.data,
            "mint_period": form.mint_period.data,
            "material": form.material.data,
            "weight": form.weight.data,
            "diameter": form.diameter.data,
            "obverse": form.obverse.data,
            "reverse": form.reverse.data,
            "grade": form.grade.data
            }
        
        artifact = Artifact(art_data)

        try:
            artifact.save()
            
            if form.image.data != None:
                file_ = form.image.data
                artifact.write_image(file_)            
            
            flash('Artifakt uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.artifacts_view", col_ref_num=col_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju artifakta!', 'error')
        
    
    for field, errors in form.errors.items():
        print(f'Field: {field}')
        for error in errors:
            flash(f'Invalid Data for {field}: {error}', 'error')
    
    
    return render_template("main_page_module/artifacts/artifacts_edit.html", form=form, artifact=artifact)


@main_page_module.route('/artifacts_delete_image/<col_ref_num>/<image_name>', methods=['GET'])
@online_required(app.config['ONLINE'])
@login_required
def artifacts_delete_image(col_ref_num, image_name):
    art_data = Artifact.get_one(col_ref_num)
    
    if art_data is False or (('user_id' not in session) and (art_data["public"] != "1")):
        flash(f'Artifakt ne obstaja.', 'error')
        return redirect(url_for('main_page_module.artifacts'))            
    
    artifact = Artifact(art_data)
    
    artifact.delete_image(image_name)
    
    flash(f'Slika izbrisana.', 'success')
    
    return render_template("main_page_module/artifacts/artifacts_view.html", artifact=artifact)


# Set the route and accepted methods
@main_page_module.route('/export_artifacts/', methods=['GET'])
@login_required
def export_artifacts():
    try:
        artifacts = Artifact.get_all("all")
    except Exception as e:
        app.logger.warn(f"{e}")

app/templates/main_page_module/artifacts/artifacts_all.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet">

{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}



{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Vsi Artifakti</a></li>
      </ol>
    </nav>
    
    <div class="row">
      <div class="col-sm-1">

      </div>
      
      
      <div class="col-sm-7">
        <legend>Artifakti</legend> 
        
        <table id="artifacts_table" class="table table-bordered" style="width:100%">
          <thead>
              <tr>
                  {% if session['user_id'] %}<th>ID</th>{% endif %}
                  <th>Naziv</th>
                  <th>Tip</th>
                  <th>Politicna Entiteta</th>
                  <th>Replika</th>
                  {% if session['user_id'] %}<th>Objavljeno</th>{% endif %}
                  <th>*</th>
              </tr>
          </thead>
          <tbody>
            {% for col_ref_num, data in Artifact.get_all(type_).items() %}
            {% set artifact = Artifact(data) %}
              <tr>
                  {% if session['user_id'] %}<td>{{ artifact.col_ref_num }}</td>{% endif %}
                  <td>{{ artifact.name }}</td>
                  <td><span class="badge text-bg-light">{{ Artifact.types(artifact.type_) }}</span></td>
                  <td>{{ artifact.state_entity }}</td>
                  <td>{% if artifact["replica"] == "1" %}<span class="badge text-bg-danger"><i class="bi bi-shield-exclamation"></i></span>{% else %}{% endif %} {{ Artifact.yes_no(artifact["replica"]) }}</td>
                  {% if session['user_id'] %}<td>{% if artifact["public"] == "1" %}<i class="bi bi-check-circle"></i>{% else %}<i class="bi bi-x-circle"></i> <i class="bi bi-incognito"></i>{% endif %} {{ Artifact.yes_no(artifact["public"]) }}</td>{% endif %}
                  <td><a class="btn btn-outline-primary" href="{{ url_for('main_page_module.artifacts_view', col_ref_num=artifact.col_ref_num) }}" role="button">Preglej</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        
      </div>


        
      <div class="col-sm-4">
        <img src="{{ url_for('static', filename='main_page_module/segment_images/freis_info.jpgGGGGG') }}" class="img-fluid" alt="...">
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
        <hr>
        <div class="d-grid gap-2">
          <div class="btn-group" role="group">
            {% if session['user_id'] %}<a class="btn btn-primary" href="{{ url_for('main_page_module.artifacts_new') }}" role="button">Dodaj nov artifakt</a>{% endif %}
            {% if session['user_id'] %}<a class="btn btn-success" href="{{ url_for('main_page_module.export_artifacts') }}" role="button"><i class="bi bi-filetype-xlsx"></i> Excel</a>{% endif %}
          </div>
        </div>
      </div>

 
      </div>
    </div>

  </div>

  
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>

  <script>
    let table = new DataTable('#artifacts_table');
  </script>

{% endblock content %}

app/templates/main_page_module/artifacts/artifacts_edit.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}

{% macro render_field(field, placeholder=None) %}
  <div class="mb-3">
      {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

      {{ field.label }}

      {% if field.errors %}
          {% set css_class = css_class + ' is-invalid' %}

          {% for error in field.errors %}
              
              <small id="{{ field.label.text }}" class="text-danger">
                  {{ error }}
            </small>

          {% endfor %}
          </ul>
      {% endif %}

      {{ field(class=css_class, autocomplete="off", placeholder=placeholder, **kwargs) }}
  </div>
{% endmacro %}


{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('main_page_module.artifacts') }}">Vsi Artifakti</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a href="{{ url_for('main_page_module.artifacts_view', col_ref_num=form.col_ref_num.data) }}">Artifakt</a></li>
        <li class="breadcrumb-item active" aria-current="page">Uredi Artifakt {{form.col_ref_num.data}}</li>
      </ol>
    </nav>
        
    <div class="row">
      <div class="col-sm-2">
        
      </div>
      
      
      <div class="col-sm-8">

        <form method="POST" action="{{ url_for('main_page_module.artifacts_edit') }}" accept-charset="UTF-8" role="form" enctype="multipart/form-data">
          {{ form.csrf_token }}
          {{ form.col_ref_num }}
  
          

          <div class="row">
            <div class="col-sm-8">
              {{ render_field(form.name, placeholder="Ime artifakta", autofocus="") }}
            </div>
            <div class="col-sm-4">
              {{ render_field(form.image) }}
            </div>
          </div>


          
          

          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.type_, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.period, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.state_entity) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.replica, class="form-select") }}
            </div>
          </div>
          
          
          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.buy_price) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.sold_price) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.joined_collection_in_year) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.left_collection_in_year) }}
            </div>
          </div>
          
          
          
          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.public, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.curr_location_of_item) }}
            </div>
            <div class="col-sm-6">
            {{ render_field(form.reference) }}
            </div>
          </div>
          
          {{ render_field(form.provenance_notes) }}
          {{ render_field(form.owners) }}
          {{ render_field(form.description) }}
          {{ render_field(form.historical_context) }}

          <div id="coins_block">
          
            <div class="row">
              <div class="col-sm-3">
                {{ render_field(form.coin_type) }}
              </div>
              <div class="col-sm-3">
                {{ render_field(form.ruler) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.mint_city) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.mint_period) }}
              </div>
            </div>
            
            <div class="row">
              <div class="col-sm-3">
                {{ render_field(form.material) }}
              </div>
              <div class="col-sm-3">
                {{ render_field(form.weight) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.diameter) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.grade, class="form-select") }}
              </div>
            </div>
            
            {{ render_field(form.coin_description) }}
            {{ render_field(form.obverse) }}
            {{ render_field(form.reverse) }}

          </div>

 

          {{ form.submit(class="form-control btn btn-dark mb-2", value="Uredi") }}


        </form>

      </div>


        
      <div class="col-sm-2">

        {% set images, count = artifact.get_images() %}
        {% if images|length == 0 %}
          <div class="carousel-item active">
          <img src="{{ url_for('static', filename='artifacts/placeholder_vector.svg') }}"  class="img-fluid">
        </div>
        {% else %}
          {% for image in images %}
          <div class="card" style="width: 18rem;">
            <img src="{{ url_for('static', filename='artifacts/images/'+image) }}"  class="img-fluid">
            <div class="card-footer">
              <a href="{{ url_for('main_page_module.artifacts_delete_image', col_ref_num=artifact.col_ref_num, image_name=image) }}" class="btn btn-danger">Izbriši</a>
            </div>
          </div>
          {% endfor %}

        {% endif %}

      </div>

 
      </div>
    </div>

  </div>

{% endblock content %}

app/templates/main_page_module/artifacts/artifacts_new.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}

{% macro render_field(field, placeholder=None) %}
  <div class="mb-3">
      {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

      {{ field.label }}

      {% if field.errors %}
          {% set css_class = css_class + ' is-invalid' %}

          {% for error in field.errors %}
              
              <small id="{{ field.label.text }}" class="text-danger">
                  {{ error }}
            </small>

          {% endfor %}
          </ul>
      {% endif %}

      {{ field(class=css_class, autocomplete="off", placeholder=placeholder, **kwargs) }}
  </div>
{% endmacro %}


{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main_page_module.artifacts') }}">Vsi Artifakti</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nov Artifakt</li>
          </ol>
        </nav>
        
    <div class="row">
      <div class="col-sm-2">
        
      </div>
      
      
      <div class="col-sm-8">

        <form method="POST" action="{{ url_for('main_page_module.artifacts_new') }}" accept-charset="UTF-8" role="form" enctype="multipart/form-data">
          {{ form.csrf_token }}

          <input type="hidden" id="col_ref_num" name="col_ref_num" value="999">
  
          {{ render_field(form.name, placeholder="Ime artifakta",
          autofocus="") }}

          

          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.type_, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.period, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.state_entity) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.replica) }}
            </div>
          </div>
          
          
          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.buy_price) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.sold_price) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.joined_collection_in_year) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.left_collection_in_year) }}
            </div>
          </div>
          
          
          
          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.public) }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.curr_location_of_item) }}
            </div>
            <div class="col-sm-6">
            {{ render_field(form.reference) }}
            </div>
          </div>
          
          {{ render_field(form.provenance_notes) }}
          {{ render_field(form.owners) }}
          {{ render_field(form.description) }}
          {{ render_field(form.historical_context) }}

          <div id="coins_block">
          
            <div class="row">
              <div class="col-sm-3">
                {{ render_field(form.coin_type) }}
              </div>
              <div class="col-sm-3">
                {{ render_field(form.ruler) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.mint_city) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.mint_period) }}
              </div>
            </div>
            
            <div class="row">
              <div class="col-sm-3">
                {{ render_field(form.material) }}
              </div>
              <div class="col-sm-3">
                {{ render_field(form.weight) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.diameter) }}
              </div>
              <div class="col-sm-3">
              {{ render_field(form.grade, class="form-select") }}
              </div>
            </div>
            
            {{ render_field(form.coin_description) }}
            {{ render_field(form.obverse) }}
            {{ render_field(form.reverse) }}

          </div>

          
          

         

          {{ form.submit(class="form-control btn btn-dark mb-2", value="Ustvari") }}


        </form>

      </div>


        
      <div class="col-sm-2">

      </div>

 
      </div>
    </div>

  </div>

{% endblock content %}